### ISSUE TITLE
[Feature] Apply labels based on author's team membership

### ISSUE THREAD

**Issue by swrobel** [srvaroa/labeler#145]
Rather than maintaining a separate list of members in this config file, it would be great to be able to reference a [Github team](https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams) that is already maintained to have an accurate list of authors. This is similar to the functionality available in [Auto Request Review](https://github.com/necojackarc/auto-request-review?tab=readme-ov-file#reviewers-configuration) by using the prefix `team:`. If this is already possible, I'd love to know how!

**Comment by srvaroa** [comment]
👍🏼

**Comment by srvaroa** [comment]
v1.11.0 (used by default in the Dockerfile @master)
