### ISSUE TITLE
feat: calculate age based on modification date

### ISSUE THREAD

**Issue by AngryMaciek** [srvaroa/labeler#146]
It would be nice to have an option which could switch the mechanism of age calculation, rather then from object creation to last modification. That way we could easily catch `stale` PRs. Right now if the setting is `1w` the following action would constantly label each PR older then a week every day (scheduled daily execution).

**Comment by srvaroa** [comment]
Makes sense, to avoid behaviour changes I prefer to solve ir with a new condition (e.g. last-updated), but good idea anyway

**Comment by srvaroa** [comment]
Hi @AngryMaciek I've pushed a draft PR for this https://github.com/srvaroa/labeler/pull/149 - I have to go AFK so I'll leave this here and give a final pass later.

Let me know if the config seems reasonable (the first two modified files in the diff are a sample and the documentation).

(if the at-least/at-most duration conditionals make sense I might add support for these in `age` too)

Cheers!

**Comment by srvaroa** [comment]
Released at v1.11.0 (now used in @master's default Dockerfile)
