### ISSUE TITLE
Support cron execution

### ISSUE THREAD

**Issue by thewtex** [srvaroa/labeler#3]
Thanks for implementing and sharing this nice Action :pray: :clap: 

Currently, the action will fail on forked pull requests per the GitHub Action permission limitations:

- https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token
- https://github.com/actions/labeler/issues/12

Could it be possible to run in a scheduled mode, i.e. cron, by examining open pull requests and labelling them?

Or, not fail when the required permissions are not available?

**Comment by srvaroa** [comment]
Thanks @thewtex! I will look into both points, not failing when perms are not available should be pretty quick but having the option to use the scheduled mode seems a better solution overall.

In the meantime PRs are of course welcome :)

**Comment by srvaroa** [comment]
The first part should be done, the action will always succeed, but log an error if something failed in the process.

I'll look into the cron next.

**Comment by thewtex** [comment]
@srvaroa awesome, thank you!! :pray:

**Comment by srvaroa** [comment]
@thewtex this one should be addressed by https://github.com/srvaroa/labeler/pull/26

**Comment by srvaroa** [comment]
Supported from v0.7, closing.
