### ISSUE TITLE
Support negative conditions

### ISSUE THREAD

**Issue by chubchenko** [srvaroa/labeler#31]
Hi, first of all, thanks for that solution 🙏 

In one of my repositories, I would like to define a list of available branch types. And if someone created a branch and has opened a PR with a name that does not match any conditions I would like to add an `unknown` label.

I tried to do that via my own conditions 
```yaml
- label: "unknown"
  branch: "^((?!feature|bugfix).)*$"
```
but then realize that it does not work since `Go` regex does not support `?!` 😞

**Comment by srvaroa** [comment]
Thanks @chubchenko, I'll try to get this done sometime soon, but PRs are welcome!

**Comment by srvaroa** [comment]
Hi @chubchenko since this is a limitation in Go's regex library I've tried an imperfect workaround. I'm interested in knowing if this would cover your use case: https://github.com/srvaroa/labeler/pull/67

**Comment by srvaroa** [comment]
Workaround merged, please refer to: https://github.com/srvaroa/labeler#negate-rules, let me know if this solves this use case. Will be released in v1.3

**Comment by chubchenko** [comment]
@srvaroa Thank you very much
