### ISSUE TITLE
Feature request: New condition based on whether the PR author has merge permissions on the target

### ISSUE THREAD

**Issue by tylerbutler** [srvaroa/labeler#41]
Hello! Thanks for the great action! This is a feature request -- if you're not open to those, no worries!

---

In some teams, people merge their own PRs once they are approved. However, when people without write access to the repo open a PR, someone on the team (that is, someone with merge permissions) needs to merge it because the author can't.

In such cases, it would be helpful to label PRs based on whether the author has write access.

**Comment by srvaroa** [comment]
Thanks @tylerbutler! Definitely open to requests (although I may not get to implementing them as fast as I'd like!)

The feature makes sense for me. I'll need to review the GH API to see whether it's possible to query for the author's permissions.

**Comment by srvaroa** [comment]
Looks like the new GH APIs should allow this based on -> https://github.com/google/go-github/blob/v50.0.0/github/repos_actions_allowed.go#L16
