### ISSUE TITLE
Option to append to existing Labels

### ISSUE THREAD

**Issue by maninder-singh-liqid** [srvaroa/labeler#42]
Please provide an option to append labels to the already existing labels on a PR.
Currently it removes all existing labels from a PR and applies those which meet the conditions. But, there are use cases where people want to manually add labels to the PR and maintain it.

**Comment by srvaroa** [comment]
Hi, thanks for suggesting this!

**Comment by srvaroa** [comment]
Hi @maninder-singh-liqid I have been double checking this and I think the behaviour you describe is the current one. There is a unit test for this here: https://github.com/srvaroa/labeler/blob/master/pkg/labeler_test.go#L88

Can you provide more info about the specific case you're seeing? Is the existing label the same as one set in the rules, or different?

**Comment by srvaroa** [comment]
@maninder-singh-liqid a valid option could be to add a configuration switch that will ONLY add append labels, but not remove them. There is a nuance: it will *never* remove them, regardless of who added them (e.g. if the action matches a rule to add a tag, but later the rule does not match, the label will stay). Would this suit you case?

**Comment by maninder-singh-liqid** [comment]
that is an option to ponder on. For my use case the current behaviour is fine. thanks for your follow up.
May be having that option would benefit someone.

**Comment by srvaroa** [comment]
@maninder-singh-liqid I pushed a PR in the `fix.42` branch. If you can give it a go to confirm this does what you expect that'd be great.

Thanks
