### ISSUE TITLE
Add support for issues

### ISSUE THREAD

**Issue by matmar10** [srvaroa/labeler#54]
This action is awesome! It works perfectly for PRs but I've noticed it doesn't work for issues. Investigating how to support this for issues as well and will try to raise a PR.

**Comment by matmar10** [comment]
I've never written a line of Go (so pardon my ignorance), but would it be as simple as updating this bit:

```Go
// HandleEvent takes a GitHub Event and its raw payload (see link below)
// to trigger an update to the issue / PR's labels.
//
// https://developer.github.com/v3/activity/events/types/
func (l *Labeler) HandleEvent(
	eventName string,
	payload *[]byte) error {

	event, err := gh.ParseWebHook(eventName, *payload)
	if err != nil {
		return err
	}
	switch event := event.(type) {
	case *gh.PullRequestEvent:
		err = l.ExecuteOn(event.PullRequest)
	case *gh.PullRequestTargetEvent:
		err = l.ExecuteOn(event.PullRequest)
	}
	// SOMETHING LIKE THIS?
	case *gh.IssueEvent:
		err = l.ExecuteOn(event.IssueEvent)
	}
	return err
}
```

I notice that each condition function has a `pr *gh.PullRequest` - I assume that may also need to be updated to point to either a PR or an Issue.

Thoughts? I can look for a Go resource to implement this as it's something we're actively using in our project (commercial sponsorship available).

**Comment by srvaroa** [comment]
Hi @matmar10 this totally makes sense. I assume we may need some extra changes to add labels on issues (although I vaguely remember that the label API works for both types). I can look into adding this (but of course PRs are welcome).

**Comment by matmar10** [comment]
Awesome @srvaroa . If it helps, we can sponsor this change with a financial incentive. If you're interested in that, please email me: matthew@launchgood.com

**Comment by srvaroa** [comment]
Thanks @matmar10, that can definitely help. I'll get in touch.

**Comment by srvaroa** [comment]
Released in https://github.com/srvaroa/labeler/releases/tag/v1.2

Thanks @matmar10 and @launchgood for sponsoring this feature!
