### ISSUE TITLE
Ignore files in PR Size condition

### ISSUE THREAD

**Issue by tshamz** [srvaroa/labeler#61]
Sometimes I want to be able to not include certain files in the calculation for number of changes. 

For example, when `yarn.lock` gets updated, it can typically include many changes that blows up the PR size condition. It would be awesome if somewhere I could list files that I don't want included in that calculation.

🙏🏻

**Comment by srvaroa** [comment]
Thanks, this makes sense. Right now we're pulling the size straight from the GH API so for this we could leverage the code in the file matcher and pull the actual diff so we can subtract the changes in that file from the totals.

**Comment by srvaroa** [comment]
Started with this. Initial PR preparing configuration here -> https://github.com/srvaroa/labeler/pull/79, I'm finishing a second with the actual feature.

**Comment by srvaroa** [comment]
Released in v1.5.0
