### ISSUE TITLE
[Feature] support local config file

### ISSUE THREAD

**Issue by javiergonzalezGenially** [srvaroa/labeler#82]
It would be great if it supported labeler.yml files that are auto generated on build time, and only fallback to fetching it through HTTP if it is not present locally.

Right now it seems unable to get it from a local file.

**Comment by srvaroa** [comment]
Thanks, this should be fairly simple to implement. I'll see if I can get to it soon (prs of course welcome).

**Comment by javiergonzalezGenially** [comment]
I wish I could, my knowledge of Go is near 0 :(
