### ISSUE TITLE
[Labeler] job no more working -- Docker build failed with exit code 1

### ISSUE THREAD

**Issue by srafiqa** [srvaroa/labeler#93]
#5 [2/3] RUN wget -q -O- https://github.com/srvaroa/labeler/releases/latest/download/action.tar.gz | tar xzvf -
  #5 0.745 wget: server returned error: HTTP/1.1 404 Not Found
  #5 0.747 tar: invalid magic
  #5 0.747 tar: short read
  #5 ERROR: process "/bin/sh -c wget -q -O- $ASSET_URL | tar xzvf -" did not complete successfully: exit code: 1
  ------
   > [2/3] RUN wget -q -O- https://github.com/srvaroa/labeler/releases/latest/download/action.tar.gz | tar xzvf -:
  0.745 wget: server returned error: HTTP/1.1 404 Not Found
  0.747 tar: invalid magic
  0.747 tar: short read
  ------
  Dockerfile:12
  --------------------
    10 |     WORKDIR /
    11 |     ARG ASSET_URL=https://github.com/srvaroa/labeler/releases/latest/download/action.tar.gz
    12 | >>> RUN wget -q -O- $ASSET_URL | tar xzvf -
    13 |     ENTRYPOINT ["/action"]
    14 |     
  --------------------
  ERROR: failed to solve: process "/bin/sh -c wget -q -O- $ASSET_URL | tar xzvf -" did not complete successfully: exit code: 1
Error: Docker build failed with exit code 1

**Comment by srvaroa** [comment]
This should get fixed with the change from @siketyan, waiting to see the release workflow complete.

**Comment by srvaroa** [comment]
![image](https://github.com/srvaroa/labeler/assets/346110/680007bd-c5ca-40fe-95b7-ca9a4506bf5b)

v1.6.3 should be fine.
