### ISSUE TITLE
Avoid referencing `latest` in Dockerfile

### ISSUE THREAD

**Issue by georgespalding** [srvaroa/labeler#95]
The Dockerfile used to fetch the binary used for the action references `latest` in all recent versions.
>ARG ASSET_URL=https://github.com/srvaroa/labeler/releases/latest/download/action.tar.gz

This is not great because it put the labeler action out of commision for *all* releases of the action, when the 1.6.2 release failed to create the `action.tar.gz` file in "latest" downloads location.

**Comment by srvaroa** [comment]
Yeah I agree with this. It's a leftover from when the action binary was compiled upon run and I kept it to avoid complicating the release process, but at this point it's safer to go that way.

I'll get this fixed soon.

Thanks!
