### ISSUE TITLE
label based on name of PR target branch

### ISSUE THREAD

**Issue by m1kesk** [srvaroa/labeler#99]
Is there an option to add label based on target branch in pull request? For example if target branch is `release/x.x.x` I would like to have label `release` on Pull request.

**Comment by srvaroa** [comment]
No, but it should be easy to add (it's a variant of the `baseBranch` option but the code should be pretty much the same)

**Comment by srvaroa** [comment]
I will close this for now as I believe the functionality is actually available with the base branch condition as mentioned above. Feel free to reopen otherwise.
